# VirgoX Elite GamingOS Version Tracking
VIRGOX_VERSION_MAJOR := 1
VIRGOX_VERSION_MINOR := 0
VIRGOX_CODENAME := Elite
VIRGOX_BUILD_DATE := $(shell date -u +%Y%m%d)
VIRGOX_BUILD_TYPE ?= UNOFFICIAL

VIRGOX_VERSION := $(VIRGOX_VERSION_MAJOR).$(VIRGOX_VERSION_MINOR)
VIRGOX_DISPLAY_VERSION := VirgoX-$(VIRGOX_CODENAME)-v$(VIRGOX_VERSION)-$(VIRGOX_BUILD_DATE)-$(VIRGOX_BUILD_TYPE)

PRODUCT_SYSTEM_PROPERTIES += \
    ro.virgox.version=$(VIRGOX_VERSION) \
    ro.virgox.display.version=$(VIRGOX_DISPLAY_VERSION) \
    ro.virgox.build.date=$(VIRGOX_BUILD_DATE) \
    ro.virgox.build.type=$(VIRGOX_BUILD_TYPE) \
    ro.virgox.codename=$(VIRGOX_CODENAME)

VIRGOX_ZIP_NAME := VirgoX-Elite-GamingOS-v$(VIRGOX_VERSION)-$(PRODUCT_DEVICE)-$(VIRGOX_BUILD_DATE)-$(VIRGOX_BUILD_TYPE)
